// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDv-hnhISwGzuyisjqjA1EYSsAk6O5PAPs',
    appId: '1:782615987908:web:682564e1cd7d483f88ab91',
    messagingSenderId: '782615987908',
    projectId: 'proyecto1-45c35',
    authDomain: 'proyecto1-45c35.firebaseapp.com',
    storageBucket: 'proyecto1-45c35.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsob8Vd_fei43aN0NVmPGDUKb4c1_IQRQ',
    appId: '1:782615987908:android:fb5e98d13872c14a88ab91',
    messagingSenderId: '782615987908',
    projectId: 'proyecto1-45c35',
    storageBucket: 'proyecto1-45c35.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTV1e4L80NOLB0FbPmdFsdEa8IPlwZL5Y',
    appId: '1:782615987908:ios:0b420d92b11f2d5988ab91',
    messagingSenderId: '782615987908',
    projectId: 'proyecto1-45c35',
    storageBucket: 'proyecto1-45c35.appspot.com',
    iosClientId: '782615987908-dctjvos65iesslvl5ebv8ml5fshtf2dj.apps.googleusercontent.com',
    iosBundleId: 'com.example.damU4Proyecto119400624',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTV1e4L80NOLB0FbPmdFsdEa8IPlwZL5Y',
    appId: '1:782615987908:ios:0b420d92b11f2d5988ab91',
    messagingSenderId: '782615987908',
    projectId: 'proyecto1-45c35',
    storageBucket: 'proyecto1-45c35.appspot.com',
    iosClientId: '782615987908-dctjvos65iesslvl5ebv8ml5fshtf2dj.apps.googleusercontent.com',
    iosBundleId: 'com.example.damU4Proyecto119400624',
  );
}
