// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6wnEswA97uYGuFNQDR1mvulptZP7KqYE',
    appId: '1:188955831403:web:9eaea8f3eebe446ffcd52e',
    messagingSenderId: '188955831403',
    projectId: 'proyecto2-f638e',
    authDomain: 'proyecto2-f638e.firebaseapp.com',
    storageBucket: 'proyecto2-f638e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClvynD2EXLjoTwAKAfjhtNJBg1GRzeL8k',
    appId: '1:188955831403:android:0633dbc66ab4c83cfcd52e',
    messagingSenderId: '188955831403',
    projectId: 'proyecto2-f638e',
    storageBucket: 'proyecto2-f638e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBU86OTDrOgYWI1DjnEqZoKWm7c6StCyro',
    appId: '1:188955831403:ios:830cd29b7676d3b6fcd52e',
    messagingSenderId: '188955831403',
    projectId: 'proyecto2-f638e',
    storageBucket: 'proyecto2-f638e.appspot.com',
    iosClientId: '188955831403-pkemrno0v3l6usl6346va6tqj8uoq423.apps.googleusercontent.com',
    iosBundleId: 'com.example.damU4Proyecto119400624',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBU86OTDrOgYWI1DjnEqZoKWm7c6StCyro',
    appId: '1:188955831403:ios:830cd29b7676d3b6fcd52e',
    messagingSenderId: '188955831403',
    projectId: 'proyecto2-f638e',
    storageBucket: 'proyecto2-f638e.appspot.com',
    iosClientId: '188955831403-pkemrno0v3l6usl6346va6tqj8uoq423.apps.googleusercontent.com',
    iosBundleId: 'com.example.damU4Proyecto119400624',
  );
}
